### ISSUE TITLE
Font not loading

### ISSUE THREAD

**Issue by rainiera** [TexasLAN/TexasLAN#13]
Tried multiple browsers on my laptop and phone, and the Lato font our source purports is not loading so it defaults to an ugly Arial.

From fonts.google.com, I would suggest a font such as Lato, or Source Sans Pro, Montserrat, or PT Sans.

**Comment by DrewRomanyk** [comment]
@samueltallent it seems like you just have to make this be https instead of http, as our website it secure and doesnt allow for downloading http stylesheets.

**Comment by samueltallent** [comment]
Fixed, thanks for the heads up @rainiera and tip @DrewRomanyk!
